MODEL:
    IF_LABELSMOOTH: 'on'
    NAME: 'resnet50'

INPUT:
    RE_PROB: 0.5 #random erasing
    SIZE: [256, 128]

DATASETS:
    NAMES: 'market1501'
    ROOT_DIR: '/home/dell/D/dell/fjw/practice/ReID/datasets'

DATALOADER:
    NUM_INSTANCE: 4
    NUM_WORKERS: 1

SOLVER:
    IMS_PER_BATCH: 32
    OPTIMIZER_NAME: 'Adam'
    MAX_EPOCH: 240
    BASE_LR: 0.00035
    
    BIAS_LR_FACTOR: 1
    WEIGHT_DECAY_BIAS: 0.0005
    WEIGHT_DECAY: 0.0005
    
    STEPS: [60, 130]
    GAMMA: 0.1
    
    WARMUP_FACTOR: 0.01
    WARMUP_ITERS: 10
    WARMUP_METHOD: 'linear'

    MARGIN : 0.3
    
    CHECKPOINT_PERIOD: 5
    LOG_PERIOD: 20
    EVAL_PERIOD: 20
    
TEST:
    IMS_PER_BATCH: 32
    RE_RANKING: 'no'
    WEIGHT: "/home/dell/D/dell/fjw/practice/ReID/MMF-Net/output/market1501/baseline15_s4+p1+p2/resnet50_model_83700.pth"  #待修改
    FEAT_NORM: 'yes'
    
OUTPUT_DIR: "/home/dell/D/dell/fjw/practice/ReID/MMF-Net/output/market1501/baseline18_s3+s4"   # 结果、模型保存路径
    
